/*Criar Tabelas*/
CREATE TABLE CRT_CARTA (
    CRT_CODIGO NUMBER(5) NOT NULL,
    CRT_SCRIPT VARCHAR2(200),
    CRT_NOME VARCHAR2(50),
    CRT_IMAGEM VARCHAR2(50),
    CRT_ATAQUE NUMBER(10),
    CRT_DEFESA NUMBER(10),
    CRT_DESCRICAO VARCHAR2(200),
    CONSTRAINT CRT_PK PRIMARY KEY(CRT_CODIGO)
);

CREATE TABLE JOG_JOGADOR (
    JOG_NOMEUSUARIO VARCHAR2(20) NOT NULL,
    JOG_NOME VARCHAR2(50),
    JOG_SENHA VARCHAR2(20),
    JOG_DATACADASTRO DATE,
    JOG_QNTDINHEIRO VARCHAR2(20),
    JOG_DTULTIMOACESSO DATE,
    CONSTRAINT JOG_PK PRIMARY KEY (JOG_NOMEUSUARIO)
);

CREATE TABLE DCK_DECK (
    DCK_NOME VARCHAR2 (20) NOT NULL,
    JOG_NOMEUSUARIO VARCHAR2 (20) NOT NULL,
    CONSTRAINT DCK_PK PRIMARY KEY(DCK_NOME, JOG_NOMEUSUARIO)
);

CREATE TABLE TOR_TORNEIO (
    TOR_NOME VARCHAR2 (20) NOT NULL,
    TOR_DTINICIO DATE,
    TOR_DESCRICAO VARCHAR2 (50),
    TOR_PREMIO VARCHAR2 (50),
    CONSTRAINT TOR_PK PRIMARY KEY (TOR_NOME, TOR_DTINICIO)
);

CREATE TABLE CMO_CARTAMONSTRO (
    CRT_CODIGO NUMBER(5) NOT NULL,
    CMO_TIPO VARCHAR2(20),
    CMO_NIVEL NUMBER(5),
    CONSTRAINT CMO_PK PRIMARY KEY (CRT_CODIGO)
);

CREATE TABLE CMA_CARTAMAGIA (
    CRT_CODIGO NUMBER(5) NOT NULL,
    CMA_EFEITOCONTINUO VARCHAR2(30),
    CONSTRAINT CMA_PK PRIMARY KEY (CRT_CODIGO)
);

CREATE TABLE CAR_CARTAARMADILHA(
    CRT_CODIGO NUMBER(5) NOT NULL,
    CONSTRAINT CAR_PK PRIMARY KEY (CRT_CODIGO)
);

CREATE TABLE CND_CARTANODECK (
    CRT_CODIGO NUMBER (5) NOT NULL,
    DCK_NOME VARCHAR2 (20) NOT NULL,
    JOG_NOMEUSUARIO VARCHAR2(20) NOT NULL,
    CND_QUANTIDADE NUMBER (3),
    CONSTRAINT CND_PK PRIMARY KEY (DCK_NOME, JOG_NOMEUSUARIO)
);

CREATE TABLE JPC_JOGADORPOSSUICARTA(
    CRT_CODIGO NUMBER (5) NOT NULL,
    JOG_NOMEUSUARIO VARCHAR2(20) NOT NULL,
    JPC_QUANTIDADE NUMBER(2),
    CONSTRAINT JPC_PK PRIMARY KEY (JOG_NOMEUSUARIO, CRT_CODIGO)
);

CREATE TABLE JPT_JOGPARTICIPATORNEIO (
    JOG_NOMEUSUARIO VARCHAR2 (5) NOT NULL,
    TOR_NOME VARCHAR2 (20) NOT NULL,
    TOR_DTINICIO DATE,
    JPT_RANKING NUMBER (2),
    CONSTRAINT JPT_PK PRIMARY KEY (TOR_NOME, TOR_DTINICIO)
);

CREATE TABLE TOP_TORNEIOPRESENCIAL(
    TOR_NOME VARCHAR2 (20) NOT NULL,
    TOR_DTINICIO DATE NOT NULL,
    TOP_LOCAL VARCHAR(2),
    TOP_ADESAO VARCHAR(10),
    CONSTRAINT TOP_PK PRIMARY KEY (TOR_NOME, TOR_DTINICIO)
);

CREATE TABLE TOO_TORNEIOONLINE(
    TOR_NOME VARCHAR2 (20) NOT NULL,
    TOR_DTINICIO DATE NOT NULL,
    TOO_PRIVADO NUMBER(1), /*BOOLEAN*/
    TOO_CHAVEDEACESSO VARCHAR2 (5),
    CONSTRAINT TOO_PK PRIMARY KEY (TOR_NOME, TOR_DTINICIO)
);

CREATE TABLE TPC_TORNEIOPREMIACARTA(
    TOR_NOME VARCHAR2(20) NOT NULL,
    TOR_DTINICIO DATE NOT NULL,
    CRT_CODIGO NUMBER(5) NOT NULL,
    TPC_QUANTIDADE NUMBER(2),
    CONSTRAINT TPC_PK PRIMARY KEY (TOR_NOME, TOR_DTINICIO)
);

CREATE TABLE PAT_PARTIDATORNEIO(
    PAT_DATAHORA DATE NOT NULL,
    PAT_VENCEDOR VARCHAR(20),
    TOR_NOME VARCHAR(20) NOT NULL,
    TOR_DTINICIO DATE NOT NULL,
    JOG_NOMEUSUARIO01 VARCHAR(20),
    JOG_NOMEUSUARIO02 VARCHAR (20),
    CONSTRAINT PAT_PK PRIMARY KEY (PAT_DATAHORA, TOR_NOME, TOR_DTINICIO)
);

ALTER TABLE CMO_CARTAMONSTRO 
  ADD CONSTRAINT CMO_FK FOREIGN KEY (CRT_CODIGO) REFERENCES CRT_CARTA (CRT_CODIGO);
  
ALTER TABLE PAT_PARTIDATORNEIO ADD (
  CONSTRAINT PAT_FK1 FOREIGN KEY (TOR_NOME, TOR_DTINICIO) REFERENCES TOR_TORNEIO (TOR_NOME,TOR_DTINICIO),
  CONSTRAINT PAT_FK3 FOREIGN KEY (JOG_NOMEUSUARIO01) REFERENCES JOG_JOGADOR (JOG_NOMEUSUARIO),
  CONSTRAINT PAT_FK4 FOREIGN KEY (JOG_NOMEUSUARIO02) REFERENCES JOG_JOGADOR (JOG_NOMEUSUARIO));
  
ALTER TABLE DCK_DECK
  ADD CONSTRAINT DCK_FK FOREIGN KEY (JOG_NOMEUSUARIO) REFERENCES JOG_JOGADOR (JOG_NOMEUSUARIO);
  
ALTER TABLE CND_CARTANODECK ADD (
  CONSTRAINT CND_FK1 FOREIGN KEY (DCK_NOME, JOG_NOMEUSUARIO) REFERENCES DCK_DECK (DCK_NOME, JOG_NOMEUSUARIO),
  CONSTRAINT CND_FK2 FOREIGN KEY (CRT_CODIGO) REFERENCES CRT_CARTA (CRT_CODIGO));

ALTER TABLE JPC_JOGADORPOSSUICARTA ADD (
  CONSTRAINT JPC_FK1 FOREIGN KEY (JOG_NOMEUSUARIO) REFERENCES JOG_JOGADOR (JOG_NOMEUSUARIO),
  CONSTRAINT JPC_FK2 FOREIGN KEY (CRT_CODIGO) REFERENCES CRT_CARTA (CRT_CODIGO));
  
ALTER TABLE CMA_CARTAMAGIA ADD CONSTRAINT CMA_FK1 FOREIGN KEY (CRT_CODIGO) REFERENCES CRT_CARTA (CRT_CODIGO);

ALTER TABLE CAR_CARTAARMADILHA ADD CONSTRAINT CAR_FK1 FOREIGN KEY (CRT_CODIGO) REFERENCES CRT_CARTA (CRT_CODIGO);

ALTER TABLE TPC_TORNEIOPREMIACARTA ADD (
  CONSTRAINT TPC_FK1 FOREIGN KEY (TOR_NOME, TOR_DTINICIO) REFERENCES TOR_TORNEIO(TOR_NOME, TOR_DTINICIO),
  CONSTRAINT TPC_FK2 FOREIGN KEY (CRT_CODIGO) REFERENCES CRT_CARTA (CRT_CODIGO));
  
ALTER TABLE TOP_TORNEIOPRESENCIAL ADD (
  CONSTRAINT TOP_FK FOREIGN KEY (TOR_NOME, TOR_DTINICIO) REFERENCES TOR_TORNEIO(TOR_NOME, TOR_DTINICIO));

ALTER TABLE TOO_TORNEIOONLINE ADD (
  CONSTRAINT TOO_FK FOREIGN KEY (TOR_NOME, TOR_DTINICIO) REFERENCES TOR_TORNEIO(TOR_NOME, TOR_DTINICIO));

ALTER TABLE JPT_JOGPARTICIPATORNEIO ADD (
  CONSTRAINT JPT1_FK FOREIGN KEY (TOR_NOME, TOR_DTINICIO) REFERENCES TOR_TORNEIO(TOR_NOME, TOR_DTINICIO),
  CONSTRAINT JPT2_FK FOREIGN KEY (JOG_NOMEUSUARIO)        REFERENCES JOG_JOGADOR(JOG_NOMEUSUARIO));

/* cria os sequences
 * Fonte: http://www.bau-de-dev.com/banco-de-dados/como-criar-um-campo-auto-increment-no-oracle
 */
CREATE SEQUENCE CRT_CODIGO_SEQ      INCREMENT BY 1 START WITH 1;


/*Deletar Tabelas
DROP TABLE CRT_CARTA;
DROP TABLE JOG_JOGADOR;
DROP TABLE DCK_DECK;
DROP TABLE TOR_TORNEIO;
DROP TABLE CMO_CARTAMONSTRO;
DROP TABLE CMA_CARTAMAGIA;
DROP TABLE CAR_CARTAARMADILHA;
DROP TABLE CND_CARTANODECK;
DROP TABLE JPC_JOGADORPOSSUICARTA;
DROP TABLE JPT_JOGPARTICIPATORNEIO;
DROP TABLE TOP_TORNEIOPRESENCIAL;
DROP TABLE TOO_TORNEIOONLINE ;
DROP TABLE TPC_TORNEIOPREMIACARTA;
DROP TABLE PAT_PARTIDATORNEIO;
*/
